from mongoengine import *


class Product(Document):
    title = StringField()
    image = StringField()
    price = DecimalField()
    comment_num = IntField()
    score = FloatField()
    company = StringField()
    model = StringField()
    date = StringField()
    os = StringField()
    cpu = StringField()
    ram = StringField()
    height = StringField()
    width = StringField()
    thickness = StringField()
    weight = StringField()
    screen_size = StringField()
    frequency = StringField()
    color = StringField()
    network_support = StringField()
    platform = StringField()
    url = URLField()
